---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: centos-6.6
    attributes:
      hadoop:
        hdfs_site:
         'dfs.datanode.max.transfer.threads': 4096
      hive:
        hive_site:
         'hive.support.concurrency': true
         'hive.zookeeper.quorum': 'localhost'
  - name: debian-6.0.10
    run_list:
    - apt::default
    attributes:
      hadoop:
        hdfs_site:
         'dfs.datanode.max.transfer.threads': 4096
      hive:
        hive_site:
         'hive.support.concurrency': true
         'hive.zookeeper.quorum': 'localhost'
  - name: ubuntu-12.04
    run_list:
    - apt::default
    attributes:
      hadoop:
        hdfs_site:
         'dfs.datanode.max.transfer.threads': 4096
      hive:
        hive_site:
         'hive.support.concurrency': true
         'hive.zookeeper.quorum': 'localhost'
  - name: ubuntu-14.04
    run_list:
    - apt::default
    attributes:
      hadoop:
        hdfs_site:
         'dfs.datanode.max.transfer.threads': 4096
      hive:
        hive_site:
         'hive.support.concurrency': true
         'hive.zookeeper.quorum': 'localhost'

suites:
  - name: mapr410
    run_list:
      - recipe[java::default]
      - recipe[hadoop_mapr::default]
    attributes:
      java:
        install_flavor: 'oracle'
        jdk_version: 7
        oracle:
          accept_oracle_download_terms: true
      hadoop_mapr:
        distribution_version: '4.1.0'
  - name: broken
    run_list:
      - recipe[hadoop::default]
    attributes: { hadoop: { distribution: 'broken' } }
